changelog_type: 'pull_request'
header_prefix: '# Changelog'
commit_changelog: false
comment_changelog: true
pull_request_title_regex: '^(Fix|Feature|Documentation|Improvement):.+$'
group_config:
  - title: 'Fix'
    labels:
      - 'Fix'
  - title: 'Feature'
    labels:
      - 'Feature'
  - title: 'Documentation'
    labels:
      - 'Documentation'
  - title: 'Improvement'
    labels:
      - 'Improvement'
