name: Changelog CI

on:
  pull_request:
    types: [ opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run Changelog CI
      uses: saadmk11/changelog-ci@v1.2.1
      with:
        config_file: .github/changelog-ci-config.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
