name: Update Changelog Version

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update Changelog
      run: |
        import re
        from datetime import datetime

        # Read the current changelog
        with open('CHANGELOG.md', 'r') as f:
            changelog = f.read()

        # Get the latest version from the changelog
        version_match = re.search(r'## \[(\d+\.\d+\.\d+)\]', changelog)
        if version_match:
            latest_version = version_match.group(1)
            major, minor, patch = map(int, latest_version.split('.'))
            new_version = f"{major}.{minor}.{patch + 1}"
        else:
            new_version = "0.1.0"

        # Add the new version to the changelog
        today = datetime.now().strftime("%Y-%m-%d")
        new_section = f"## [{new_version}] - {today}\n\n"
        updated_changelog = re.sub(r'# Changelog\n', f'# Changelog\n\n{new_section}', changelog)

        # Write the updated changelog
        with open('CHANGELOG.md', 'w') as f:
            f.write(updated_changelog)

      shell: python
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CHANGELOG.md
        git commit -m "Update changelog with new version" || echo "No changes to commit"
        git push
